# Generated by Django 3.1 on 2020-08-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleacesso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
    ]
